// Punto de entrada de los datos: usa Supabase si está configurado
// (src/config.js) y si no, el almacenamiento local del navegador.

import * as local from './data-local.js';
import * as remote from './data-remote.js';
import { CLOUD } from './config.js';

export { CLOUD };

const impl = CLOUD ? remote : local;
const call = (name) => (...args) => impl[name](...args);

export const currentUser = call('currentUser');
export const saveUser = call('saveUser');
export const switchUser = call('switchUser');
export const createAccount = call('createAccount');
export const signIn = call('signIn');
export const resetPassword = call('resetPassword');
export const setPassword = call('setPassword');
export const signOut = call('signOut');
export const loginEmail = call('loginEmail');
export const finishEmailLink = call('finishEmailLink');
export const sessionToken = call('sessionToken');
export const adoptSession = call('adoptSession');
export const listUsers = call('listUsers');
export const listAccounts = call('listAccounts');
export const moveUserPets = call('moveUserPets');
export const adminDeleteUser = call('adminDeleteUser');
export const adminDeletePet = call('adminDeletePet');
export const registerPet = call('registerPet');
export const trainingPhotos = call('trainingPhotos');
export const myPets = call('myPets');
export const getPet = call('getPet');
export const allPets = call('allPets');
export const savePet = call('savePet');
export const removeMyPet = call('removeMyPet');
export const createPetGift = call('createPetGift');
export const petGiftInfo = call('petGiftInfo');
export const acceptPetGift = call('acceptPetGift');
export const reportLost = call('reportLost');
export const facebookPage = call('facebookPage');
export const markRecovered = call('markRecovered');
export const lostAlert = call('lostAlert');
export const myArea = call('myArea');
export const setMyArea = call('setMyArea');
export const clearMyArea = call('clearMyArea');
export const reportFound = call('reportFound');
export const confirmFound = call('confirmFound');
export const logTagVisit = call('logTagVisit');
export const tagStats = call('tagStats');
export const claimFound = call('claimFound');
export const getFound = call('getFound');
export const allFound = call('allFound');
export const saveFound = call('saveFound');
export const deleteFound = call('deleteFound');
export const notify = call('notify');
export const notifyAll = call('notifyAll');
export const deliverPending = call('deliverPending');
export const enablePush = call('enablePush');
export const pushConfigured = call('pushConfigured');
export const savePushKey = call('savePushKey');
export const myNotifications = call('myNotifications');
export const markRead = call('markRead');
export const latestSuccesses = call('latestSuccesses');
export const getSuccess = call('getSuccess');
export const deleteSuccess = call('deleteSuccess');
export const commentsFor = call('commentsFor');
export const addComment = call('addComment');
export const deleteComment = call('deleteComment');
export const countComments = call('countComments');
export const addSuccess = call('addSuccess');
export const isAdmin = call('isAdmin');
export const claimAdmin = call('claimAdmin');
export const adminExists = call('adminExists');
export const contactAdmin = call('contactAdmin');
export const listContacts = call('listContacts');
export const markContactRead = call('markContactRead');
export const deleteContact = call('deleteContact');
export const studyAccess = call('studyAccess');
export const studySave = call('studySave');
export const studyList = call('studyList');
export const studyFile = call('studyFile');
export const studyGuests = call('studyGuests');
export const studyNewGuest = call('studyNewGuest');
export const studyDeleteGuest = call('studyDeleteGuest');
export const studyJoin = call('studyJoin');
